#pragma once

// From glfw3.h
#define MAAT_MOUSE_BUTTON_1         0
#define MAAT_MOUSE_BUTTON_2         1
#define MAAT_MOUSE_BUTTON_3         2
#define MAAT_MOUSE_BUTTON_4         3
#define MAAT_MOUSE_BUTTON_5         4
#define MAAT_MOUSE_BUTTON_6         5
#define MAAT_MOUSE_BUTTON_7         6
#define MAAT_MOUSE_BUTTON_8         7
#define MAAT_MOUSE_BUTTON_LAST      MAAT_MOUSE_BUTTON_8
#define MAAT_MOUSE_BUTTON_LEFT      MAAT_MOUSE_BUTTON_1
#define MAAT_MOUSE_BUTTON_RIGHT     MAAT_MOUSE_BUTTON_2
#define MAAT_MOUSE_BUTTON_MIDDLE    MAAT_MOUSE_BUTTON_3